apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
      type: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    type: node
spec:
    replicas: 2
    selector:
      matchLabels:
        type: node
    template:
      metadata:
        name: node-pod
        labels:
          type: node
      spec:
        containers:
         - name: node
           image: bhargav933/node-app:7
